#!/bin/bash
# Basic range in for loop

#rm -r *.exr
#rm -r *.png

for value in {1..360}
do
  echo Render frame $value \n 
  if [ $value -le 227 ]
  then
    echo render normal scene \n
    ./pbrt-v3/cmake-build-release/pbrt ./scenes/sceneA.pbrt --fn $value --tf 2 
  else
    echo render shattered cone \n
    ./pbrt-v3/cmake-build-release/pbrt ./scenes/sceneB.pbrt --fn $value --tf 2 
  fi
done

echo All done

