#!/bin/bash
# Render a range of images in PBRT

rm -r *.exr
rm -r *.png

for value in {1..360}
do
  echo Render frame $value
  if [ $value -le 227 ]
  then
    echo render normal scene
    ./release/pbrt ./scenes/sceneA.pbrt --fn $value --tf 2 
  else
    echo render shattered cone
    ./release/pbrt ./scenes/sceneA.pbrt --fn $value --tf 2 
  fi
done

echo Finisched rendering

